### ISSUE TITLE
User settings Modal

### ISSUE THREAD

**Issue by ArjunBhuptani** [ConnextProject/ethcalate-2waypayment#10]
Show name and phone, update name, update phone

**Comment by ArjunBhuptani** [comment]
TO DO:
- [ ] Fix 400 bad request error on updateName. (Not coming from hub, I checked)
- [ ] UX improvements
- [ ] Fix modal appearing only on bottom of screen
- [ ] Test updatePhone

**Comment by LayneHaber** [comment]
If I have no channels, can I still update my settings and get stored as a user?
