### ISSUE TITLE
Flag Challenge or Suggested Challenge

### ISSUE THREAD

**Issue by LayneHaber** [ConnextProject/ethcalate-2waypayment#14]

**Comment by ArjunBhuptani** [comment]
If party A closes the channel with a lower nonced message, the hub needs to suggest it's most recent nonced update to party B for them to challenge the update. Then party B needs to be able to submit that update.

Needs:
1) Hub needs to know nonce when channel goes into challenge period
2) Hub saves nonce to latestnonce in channel db entry and updates channel status to challenge
3) If nonce < latestnonce, Hub sends a phone message to the user
4) During getChannels(), dApp needs to check if latestnonce < most recent nonced transaction
end state) dApp alerts user when someone attempts to close with nonce < latestnonce

**Comment by ArjunBhuptani** [comment]
Crap, this can't be tested until metamask is fixed

**Comment by rhlsthrm** [comment]
https://github.com/ConnextProject/ethcalate-2waypayment/pull/42

https://github.com/ConnextProject/ethcalate-hub/pull/2
