### ISSUE TITLE
Error handling + error UX + loading UX

### ISSUE THREAD

**Issue by ArjunBhuptani** [ConnextProject/ethcalate-2waypayment#20]
- [x] Channels are being retrieved and ethcalate is instantiating contract instance loading

- [x] Warning when challenge period is too short (less than 1 day?)

- [x] Join channel modal confirmation, maybe have something that alerts the agentB to the proposed channel challenge time..?

- [x] Update state modal success and error messages, figure better way to update channel balance after tx

**Comment by LayneHaber** [comment]
Loading ux handled for when channels are being retrieved and ethcalate is instantiating the contract instance

**Comment by LayneHaber** [comment]
case where you try to join a channel with yourself (i.e. despositA is non-zero and you try to join as agentA)

**Comment by LayneHaber** [comment]
everything just force reloads (i.e. reinits the ethcalate contracts and myChannels) after the ethcalate client calls are made. not ideal, should be improved upon in v0.1
