### ISSUE TITLE
Bug: "Waiting for counterparty to join channel" shows up if you send all of your deposit too

### ISSUE THREAD

**Issue by ArjunBhuptani** [ConnextProject/ethcalate-2waypayment#34]
To recreate:

1) Open channel and have acct 2 join
2) Send all of deposit to acct 2
3) Click on channel in accordion

**Comment by rhlsthrm** [comment]
The send button shouldn't show up if you're waiting for a join right? Also I would expect the tx to fail with a revert exception.

**Comment by ArjunBhuptani** [comment]
Fixed through other updates
