### ISSUE TITLE
Vulnerability making closing channel impossible

### ISSUE THREAD

**Issue by jtremback** [ConnextProject/ethcalate-2waypayment#50]
If I call `updateState` with our latest tx and then refuse to sign a tx with a higher nonce, it will be impossible for you to call `startChallenge`, because `startChallenge` calls `updateState`, which has the assertion `require(nonce > channel.nonce);`. 

At this point I will demand a payment of half the value that you have in the channel to release it

**Comment by rhlsthrm** [comment]
Good catch here. I see two possible fixes to this:
* Only allow `updateState` to be called when status is `challenge` (but this removes the ability to "checkpoint" on chain).
* Allow `startChallenge` to be called using the last on-chain checkpointed state (i.e. you don't need to submit a signed tx to start challenge).

What do you think is a better option? I'm leaning towards the second option.

**Comment by jtremback** [comment]
In Guac, we use the second option. You just have to make two calls. You could even have a method that combines the calls for convenience, but I don't think it would get used because off chain code would always just want to 

- check the latest state
- submit our state if later
- call closeChannel

**Comment by rhlsthrm** [comment]
https://github.com/ConnextProject/ethcalate-2waypayment/pull/62
https://github.com/ConnextProject/ethcalate-hub/pull/3

**Comment by rhlsthrm** [comment]
Fixed, but I think some UX changes are needed around it.
