### ISSUE TITLE
VM Exception: Revert when trying to initiate challenge period

### ISSUE THREAD

**Issue by ArjunBhuptani** [ConnextProject/ethcalate-2waypayment#67]
*Expected:*
Channel enters challenge period after "start close channel" is submitted

*Actual:*
```Error: Error: Error: [ethjs-rpc] rpc error with payload {"id":229647289188,"jsonrpc":"2.0","params":["0xf88a09843b9aca00835b8d8094f25186b5081ff5ce73482ad761db0eb0d25abfbf80a4ff2f0275a72afc98328bed707baff8bd771c7cc27f7da024de59a482e2c745f8bc4ca7d58222e2a0cefbe40e806a5b9e0be816011e42a9215cc7c220d2e8447a03e1d9e52e0d78a8a0747dcc175ebf7f5410451cbc3eb6e9bbf4b2b93e38e4ecce0dfe005584ff328c"],"method":"eth_sendRawTransaction"} Error: VM Exception while processing transaction: revert```

*To reproduce:*
From existing channel with confirmed updates:
1) Update state onchain
2) Start close channel button
3) Hit close

**Comment by rhlsthrm** [comment]
This wasn't the issue, the issue was from the event not getting caught by the listener.
