### ISSUE TITLE
Checkpointing the channel doesn't seem to work

### ISSUE THREAD

**Issue by ArjunBhuptani** [ConnextProject/ethcalate-2waypayment#96]
To repro:

Open channel, send a bunch of moneyshots, try to checkpoint a state update.

The transaction confirms, but, when you click `close channel`, only the original deposits are shown.

**Comment by ArjunBhuptani** [comment]
Seems to be working, but doesn't actually show up in the close channel modal UX

**Comment by ArjunBhuptani** [comment]
Sometimes shows up apparently... what the hell

**Comment by rhlsthrm** [comment]
This might be still due to the fact that some of our API endpoints intermittently take forever to resolve.
